apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-dep
  namespace: chap4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timesheet
  template:
    metadata:
      labels:
        app: timesheet
    spec:
      containers:
        - name: timesheet
          image: dinamechergui7992/timesheet:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: timesheet-config
            - secretRef:
                name: timesheet-secret
