apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timesheet
  template:
    metadata:
      labels:
        app: timesheet
    spec:
      containers:
        - name: timesheet
          image: dinamechergui7992/timesheet:1.1
          ports:
            - containerPort: 8080
